config/routes.rb
Rails.application.routes.draw do
  resources :logins 
    
  root "logins#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :skills
  resources :groups
  resources :contacts
  get 'home/index'
  get 'home/new'
  
  devise_for :users

end

app/models/group.rb
class Group < ActiveRecord::Base
	
	has_and_belongs_to_many :contacts
	has_and_belongs_to_many :skills
	
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @contacts = Contact.all
    @skills = Skill.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @contacts = Contact.all
    @skills = Skill.all
  end

  # GET /groups/new
  def new
    @group = Group.new
    @contacts = Contact.all
    @skills = Skill.all
  end

  # GET /groups/1/edit
  def edit
    @contacts = Contact.all
    @skills = Skill.all
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @contacts = Contact.all
    @skills = Skill.all
    checked_skills = check_skills_using(params[:skill_list])
    uncheck_missing_skills(@skills, checked_skills)
    
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @contacts = Contact.all
    @skills = Skill.all
    checked_skills = check_skills_using(params[:skill_list])
    uncheck_missing_skills(@skills, checked_skills)
    
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    @contacts = Contact.all
    @skills = Skill.all
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def check_skills_using( skill_id_array )
    checked_skills = []
    checked_params = skill_id_array || []
    for check_box_id in checked_params
      skill = Skill.find(check_box_id)
      if not @group.skills.include?(skill)
        @group.skills << skill
      end
      checked_skills << skill
    end
    return checked_skills
  end
  
  def uncheck_missing_skills( skills, checked_skills)
    missing_skills = skills- checked_skills
    for skill in missing_skills
      if @group.skills.include?(skill)
         @group.skills.delete(skill)
       end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => "form-horizontal group" } do |f| %>

    <% if @group.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@group[:name]) %>
  </div><br><br>

<h1>Skills</h1>
<table class="table table-striped">
  <% for skill in @skills %>
  <tr>
  <td>
   <%= check_box_tag('skill_list[]', skill.id, @group.skills.collect {|obj| obj.id}.include?(skill.id)) %>
 &nbsp; <%= skill.name %>
        </td></tr>
  <% end -%>
  </table><br><br>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            groups_path, :class => 'btn btn-default' %>

<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr  class="danger">
      
      <th><%= model_class.human_attribute_name(:name) %></th>
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr >
       <!--  <td><%= link_to group.id, group_path(group) %></td> -->
        <td><%= group.name %></td>
        <!-- <td><%=l group.created_at %></td> -->
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %> <br><br><br>
   <b class="text-success">Total No.of groups: <%= @groups.size %></b>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>