config/routes.rb
Rails.application.routes.draw do
  resources :logins 
    
  root "logins#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :skills
  resources :groups
  resources :contacts
  get 'home/index'
  get 'home/new'
  
  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! 
	def index
		@contacts = Contact.all
		@groups = Group.all
		@skills = Skill.all
	 	if user_signed_in? 		
	 		redirect_to :controller => 'home', :action => 'new' 
	 			
	 	else
	 		 redirect_to '/admin/login' 	
	 	end 
	end

	def new
		@contacts = Contact.all
		@groups = Group.all
		@skills = Skill.all
		respond_to do |format|
		format.html { render :new }
	end
	end
	def edit
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <title>Associations</title>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->

        <!-- Top Menu Items -->

        <div class="container">

            <div class="row">

                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="row">
                                
                                <div class="col-xs-6">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>

                                <div class="col-xs-9 text-right">
                                    <div class="huge">
                                        <%=Contact.all.size%>
                                    </div><br>
                                    <div>Total No.of Contacts!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left"><%= link_to 'Add New Contact', new_contact_path %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6">
                                    <i class="fa fa-th-large fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">
                                        <%=Group.all.size%>
                                    </div><br>
                                    <div>Total No.of Groups!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left"><%= link_to 'Add New Group' ,new_group_path%></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6">
                                    <i class="fa fa-key fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">
                                        <%=Skill.all.size%>
                                    </div><br>
                                    <div>Total No.of skills!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left"><%= link_to 'Add New Skill' ,new_skill_path%></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.Contacts Panel -->
            <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title" , style="color:brown;"><i class="fa fa-users fa-fw"></i> Contacts Panel</h3>
                    </div>
                    <div class="panel-body">
                        <% @contacts.each do |contact| %>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th> <i class="fa fa-fw fa-user"></i>
                                                <%=contact.Name %>
                                            </th>
                                        </tr>
                                    </thead>
                                </table>
                                <% end %>
                            </div>
                            <div class="text-right">
                                <%=link_to 'View All Contacts', contacts_path %> <i class="fa fa-arrow-circle-right"></i>
                            </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- /.Groups Panel -->
    <div class="col-lg-6 col-md-6">
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" , style="color:brown;"><i class="fa fa-th-large fa-fw"></i> Groups Panel</h3>
                </div>
                <div class="panel-body">
                    <div class="accordion">
                        <h2 class="acc_trigger"><a href="#">
                              <% @groups.each do |group| %></a>
                            </h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <tr>
                                    <th class="clicker" id="<%=group.name.downcase.remove(" ")%>"> <i class="fa fa-fw fa-th-large"></i>
                                        <%=group.name %>
                                            <i class="fa fa-fw fa-chevron-down" style="float:right;"></i>
                                    </th>
                                </tr>
                                <tbody>

                                    <% group.contacts.each do |contact| %>
                                        <tr class="<%=group.name.downcase.remove(" ")%>_shower shower">
                                            <td>
                                                <%=contact.Name%>
                                            </td>
                                        </tr>
                                        <% end %>
                                </tbody>
                            </table>
                        </div>
                        <% end %>
                    </div>
                    <div class="text-right">
                        <%=link_to 'View All Groups', groups_path %> <i class="fa fa-arrow-circle-right"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <!-- /.Groups Blocks & Skills under Contacts -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" , style="color:brown;">
                    <i class="fa fa-list-alt fa-fw"></i> 
                    Groups Blocks & Skills under Contacts
                 </h3>
                </div>
                <div class="panel-body">
                    <div class="panel-group" id="accordion">
                        <a href="#">
                            <% @groups.each do |group| %>
                        </a>
                        <div class="panel panel-default" style="float:left; width:190px; margin:0px 0px 0px 23px ">
                            <div class="panel-heading">
                                <h1 class="panel-title" > 
                                    <%= group.name %> 
                                     
                                </h1>
                                <div class="panel-body">
                                    <% group.skills.each do |skill| %>
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                    <th class="skclick" id="<%=skill.name%>_<%=group.name%>">
                                                        <%=skill.name %>
                                         <i class="fa fa-fw fa-chevron-down" style="float:right;"></i>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <% skill.contacts.each do |contact|%>
                                 <tr class="<%=skill.name%>_<%=group.name%>_skshow skshow">
                                                <td>
                                                    <%= contact.Name %>
                                                </td>

                                            </tr>
                                             
                                            </tbody>
                                             <% end %>
                                        </table>
                                       <% end %>
                                </div>
                            </div>
                        </div>
                     <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>
<script>
    $(document).ready(function() {
        $(".shower").hide();
        $(".clicker").click(function() {
            mydiv = "." + $(this).attr("id") + "_shower";
            $(mydiv).toggle();

        });
        $(".skshow").hide();
        $(".skclick").click(function() {
            mydiv1 = "." + $(this).attr("id") + "_skshow";
            $(mydiv1).toggle();
            

            });
    });
</script>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/new.html.erb
<%= render 'form' %>