config/routes.rb
Rails.application.routes.draw do
  resources :logins 
    
  root "logins#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :skills
  resources :groups
  resources :contacts
  get 'home/index'
  get 'home/new'
  
  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <%=content_for?(:title) ? yield(:title) : "Company" %>
    </title>
    <%=csrf_meta_tags %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

        <%=stylesheet_link_tag "application", :media=> "all" %>

            <!-- For third-generation iPad with high-resolution Retina display: -->
            <!-- Size should be 144 x 144 pixels -->
            <%=favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel=> 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

                <!-- For iPhone with high-resolution Retina display: -->
                <!-- Size should be 114 x 114 pixels -->
                <%=favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel=> 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

                    <!-- For first- and second-generation iPad: -->
                    <!-- Size should be 72 x 72 pixels -->
                    <%=favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel=> 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

                        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
                        <!-- Size should be 57 x 57 pixels -->
                        <%=favicon_link_tag 'apple-touch-icon-precomposed.png', :rel=> 'apple-touch-icon-precomposed', :type => 'image/png' %>

                            <!-- For all other devices -->
                            <!-- Size should be 32 x 32 pixels -->
                            <%=favicon_link_tag 'favicon.ico', :rel=> 'shortcut icon' %>

                                <%=javascript_include_tag "application" %>
</head>

<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
               
            </button>
            <div class="navbar-collapse collapse navbar-responsive-collapse">

                <ul class="nav navbar-nav ">
                    <li class="active">
                        <h2><a href= "#"> <%= link_to "Associations" , logins_path %></a></h2>
                    </li>
                </ul>
                <ul class="nav navbar-right top-nav">
                    <li class="dropdown">
                        <a href="#" style="color:#fff;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="divider"></li>
                            <li>
                                <i class="fa fa-fw fa-power-off"></i><%= link_to "sign out", destroy_user_session_path, :method => :delete ,:class=> 'pull-top'%>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            </nav>
        </div>


            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<% if current_user.present? %>
<div class="dash">

  <ul class="nav navbar-left top-nav" >
<div class="col-md-2" >
    <ul class="nav nav-pills nav-stacked" >
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <div class="nav navbar-nav side-nav"  > 

            <table >
                    <tr>
                    <%= link_to 'Dashboard', home_new_path , :class => "fa fa-fw fa-dashboard" , :style => "color:#fff"%> 
                     
                </tr>
                <br>
                <br>
                <br>
                <tr >
                 
                      <%=link_to 'Contacts', contacts_path , :class => "fa fa-fw fa-users",  :style => "color:#fff"%></i>
             
               </tr >
                <br>
                <br>
                <br>
                 <tr >
                    
                    <%=link_to 'Groups', groups_path, 
                    :class => "fa fa-fw fa-list" ,:style => "color:#fff" %></i> 
                    
                </tr >
                <br>
                <br>
                <br>
                <tr >
                    
                 <%=link_to 'Skills', skills_path , 
                 :class => "fa fa-fw fa-edit", :style => "color:#fff"%></i>
                    </i>
                                        </tr >
            </table>
                <br>
                <br>
                <br>
              </div>
             </div> 
        </div>
    </div>
    <% end %>
</body>
</div>
<br>
<br>
<br><br>
<br>
<div class="container main">
        <div class="row">
            <div class="col-lg-9">
                <%=bootstrap_flash %>
                    <%=yield %>
            </div>
        </div>
    </div>


</div>
</html>